done

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,10 +2,26 @@ name: main
 on: [push]
 jobs:
   build:
-     runs-on: ubuntu-latest
-     steps:
-     - name: Checkout code
-       run: actions/checkout@v2
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+    
+    - name: Setup node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '18'
+    
+    - name: install package.json
+      run: npm install
+    
+    - name: Run Test1
+      run: |
+        output=$(node dist/Test1.js)
+        exit_code=$output
 
-       - name: print html
-       run: cat hellome.html
+        if [ $exit_code -ne 0 ]; then
+          echo "Error $exit_code"
+          exit 1
+        fi
+
